import { Mail } from "../schema";
export type { Mail };

export const mails: Mail[] = [
  {
    id: "6c84fb90-12c4-11e1-840d-7b25c5ee775a",
    reference: "ARR-2026-02-23-0012",
    receivedAt: new Date("2026-02-23T10:30:00"),
    emittedAt: new Date("2026-02-21T08:15:00"),
    sender: "Ministère de la Culture et de la Francophonie",
    senderType: "ADMINISTRATION",
    officialName: "Ministère de la Culture et de la Francophonie",
    identificationNumber: "GOV-CIV-1001",
    phone: "+225 01 23 45 67 89",
    email: "contact@culture.gouv.ci",
    senderOrganization: "Cabinet du Ministre",
    recipientService: "Secrétariat Permanent - CNF",
    object:
      "Note d'orientation concernant l'organisation de la Semaine Nationale de la Francophonie 2026 et la coordination des activités culturelles avec les partenaires internationaux de l'OIF.",
    type: "COURRIER_ARRIVEE",
    priority: "URGENT",
    confidentiality: "CONFIDENTIEL",
    status: "EN_TRAITEMENT",
    pageCount: 2,
    registeredBy: "Agent Koné",
    scanUrl: "/Courrier.pdf",
    read: true,
  },
  {
    id: "110e8400-e29b-11d4-a716-446655440000",
    reference: "INT-2026-02-20-0045",
    receivedAt: new Date("2026-02-20T14:15:00"),
    emittedAt: new Date("2026-02-19T10:00:00"),
    sender: "Direction des Ressources Humaines",
    senderType: "ADMINISTRATION",
    officialName: "Direction des Ressources Humaines",
    identificationNumber: "GOV-CIV-2045",
    phone: "+225 05 55 55 55 55",
    email: "drh@cnf.gouv.ci",
    senderOrganization: "DRH - CNF",
    recipientService: "Tous les Départements",
    object:
      "Note de service portant sur les nouvelles modalités de formation continue des agents et le programme de bourses de mobilité au sein de l'espace francophone pour l'année budgétaire en cours.",
    type: "NOTE_INTERNE",
    priority: "URGENT",
    confidentiality: "NORMAL",
    status: "TRANSMIS",
    pageCount: 1,
    registeredBy: "Agent Sylla",
    read: true,
  },
  {
    id: "3b241101-e2bb-11d4-a716-446655440000",
    reference: "DEP-2026-02-18-0003",
    receivedAt: new Date("2026-02-18T09:00:00"),
    emittedAt: new Date("2026-02-17T16:30:00"),
    sender: "Direction de la Coopération Internationale",
    senderType: "ADMINISTRATION",
    officialName: "Commission Nationale de la Francophonie - Département Coopération",
    identificationNumber: "GOV-CIV-8012",
    phone: "+225 01 02 03 04 05",
    email: "cooperation@cnf.gouv.ci",
    senderOrganization: "Secrétariat Permanent",
    recipientService: "Ministère des Affaires Étrangères",
    object:
      "Transmission du rapport annuel de coopération multilatérale francophone et état d'avancement des projets de promotion de la diversité culturelle et linguistique financés par le fonds spécial.",
    type: "COURRIER_DEPART",
    priority: "NORMAL",
    confidentiality: "NORMAL",
    status: "ARCHIVE",
    pageCount: 15,
    registeredBy: "Agent Bamba",
    scanUrl: "/Courrier.pdf",
    read: true,
  },
  {
    id: "3b241101-e2bb-11d4-a716-446655440001",
    reference: "ARR-2026-02-22-0015",
    receivedAt: new Date("2026-02-22T16:45:00"),
    emittedAt: new Date("2026-02-20T11:20:00"),
    sender: "Agence Universitaire de la Francophonie (AUF)",
    senderType: "ONG",
    officialName: "AUF - Bureau Afrique de l'Ouest",
    identificationNumber: "AUF-CIV-3022",
    phone: "+225 27 22 44 12 34",
    email: "contact@auf.org",
    senderOrganization: "Direction Régionale",
    recipientService: "Département de la Promotion de la Langue",
    object:
      "Demande de partenariat pour la mise en œuvre de centres d'employabilité francophones et soutien logistique pour le déploiement des campus numériques dans les universités publiques.",
    type: "COURRIER_ARRIVEE",
    priority: "NORMAL",
    confidentiality: "NORMAL",
    status: "ENREGISTRE",
    pageCount: 3,
    registeredBy: "Agent Koné",
    read: false,
  },
];
