import { Mail } from "../schema";

export interface Correspondent {
  id: string;
  name: string;
  type: "ADMINISTRATION" | "ONG" | "ENTREPRISE" | "PERSONNE" | "AUTRE";
  email?: string;
  phone?: string;
  totalSent: number;
  totalReceived: number;
  lastExchangeDate: Date;
  mails: Mail[];
}

export const correspondents: Correspondent[] = [
  {
    id: "corr-001",
    name: "Ministère de la Culture et de la Francophonie",
    type: "ADMINISTRATION",
    email: "contact@culture.gouv.ci",
    phone: "+225 01 23 45 67 89",
    totalSent: 12,
    totalReceived: 18,
    lastExchangeDate: new Date("2026-03-28T10:30:00"),
    mails: [
      {
        id: "m-001-a",
        reference: "ARR-2026-03-28-0012",
        receivedAt: new Date("2026-03-28T10:30:00"),
        emittedAt: new Date("2026-03-27T08:15:00"),
        sender: "Ministère de la Culture et de la Francophonie",
        senderType: "ADMINISTRATION",
        senderOrganization: "Cabinet du Ministre",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Note d'orientation concernant l'organisation de la Semaine Nationale de la Francophonie 2026",
        type: "COURRIER_ARRIVEE",
        priority: "URGENT",
        confidentiality: "CONFIDENTIEL",
        status: "EN_TRAITEMENT",
        pageCount: 2,
        registeredBy: "Agent Koné",
        read: true,
        email: "contact@culture.gouv.ci",
        phone: "+225 01 23 45 67 89",
        scanUrl: "/demo-scan.pdf",
      },
      {
        id: "m-001-b",
        reference: "DEP-2026-03-20-0008",
        receivedAt: new Date("2026-03-20T09:00:00"),
        emittedAt: new Date("2026-03-19T14:30:00"),
        sender: "Secrétariat Permanent - CNF",
        senderType: "ADMINISTRATION",
        senderOrganization: "Secrétariat Permanent",
        recipientService: "Ministère de la Culture et de la Francophonie",
        object:
          "Proposition de programme pour la Journée internationale de la Francophonie",
        type: "COURRIER_DEPART",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "TRANSMIS",
        pageCount: 5,
        registeredBy: "Agent Sylla",
        read: true,
        email: "contact@culture.gouv.ci",
        phone: "+225 01 23 45 67 89",
        scanUrl: "/demo-scan.pdf",
      },
      {
        id: "m-001-c",
        reference: "ARR-2026-03-10-0003",
        receivedAt: new Date("2026-03-10T11:00:00"),
        emittedAt: new Date("2026-03-09T09:00:00"),
        sender: "Ministère de la Culture et de la Francophonie",
        senderType: "ADMINISTRATION",
        senderOrganization: "Direction de la Francophonie",
        recipientService: "Direction de la Coopération - CNF",
        object:
          "Demande de rapport sur les activités de promotion linguistique du premier trimestre",
        type: "COURRIER_ARRIVEE",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "CLOTURE",
        pageCount: 1,
        registeredBy: "Agent Bamba",
        read: true,
      },
      {
        id: "m-001-d",
        reference: "DEP-2026-02-28-0015",
        receivedAt: new Date("2026-02-28T16:00:00"),
        emittedAt: new Date("2026-02-27T10:00:00"),
        sender: "Secrétariat Permanent - CNF",
        senderType: "ADMINISTRATION",
        senderOrganization: "Secrétariat Permanent",
        recipientService: "Ministère de la Culture et de la Francophonie",
        object:
          "Transmission du bilan annuel des activités de la Commission Nationale",
        type: "COURRIER_DEPART",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "ARCHIVE",
        pageCount: 22,
        registeredBy: "Agent Koné",
        read: true,
      },
    ],
  },
  {
    id: "corr-002",
    name: "Agence Universitaire de la Francophonie (AUF)",
    type: "ONG",
    email: "contact@auf.org",
    phone: "+225 27 22 44 12 34",
    totalSent: 8,
    totalReceived: 14,
    lastExchangeDate: new Date("2026-03-25T14:00:00"),
    mails: [
      {
        id: "m-002-a",
        reference: "ARR-2026-03-25-0020",
        receivedAt: new Date("2026-03-25T14:00:00"),
        emittedAt: new Date("2026-03-24T11:20:00"),
        sender: "Agence Universitaire de la Francophonie (AUF)",
        senderType: "ONG",
        senderOrganization: "Direction Régionale",
        recipientService: "Département de la Promotion de la Langue",
        object:
          "Demande de partenariat pour la mise en œuvre de centres d'employabilité francophones",
        type: "COURRIER_ARRIVEE",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "ENREGISTRE",
        pageCount: 3,
        registeredBy: "Agent Koné",
        read: false,
      },
      {
        id: "m-002-b",
        reference: "DEP-2026-03-15-0011",
        receivedAt: new Date("2026-03-15T09:30:00"),
        emittedAt: new Date("2026-03-14T16:00:00"),
        sender: "Secrétariat Permanent - CNF",
        senderType: "ADMINISTRATION",
        senderOrganization: "Secrétariat Permanent",
        recipientService: "AUF - Bureau Afrique de l'Ouest",
        object:
          "Réponse à la proposition de partenariat sur les campus numériques",
        type: "COURRIER_DEPART",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "TRANSMIS",
        pageCount: 2,
        registeredBy: "Agent Sylla",
        read: true,
      },
      {
        id: "m-002-c",
        reference: "ARR-2026-02-20-0007",
        receivedAt: new Date("2026-02-20T10:45:00"),
        emittedAt: new Date("2026-02-19T15:30:00"),
        sender: "Agence Universitaire de la Francophonie (AUF)",
        senderType: "ONG",
        senderOrganization: "Direction Régionale",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Invitation à la conférence régionale sur l'enseignement supérieur francophone",
        type: "COURRIER_ARRIVEE",
        priority: "URGENT",
        confidentiality: "NORMAL",
        status: "CLOTURE",
        pageCount: 4,
        registeredBy: "Agent Bamba",
        read: true,
      },
    ],
  },
  {
    id: "corr-003",
    name: "Organisation Internationale de la Francophonie (OIF)",
    type: "ONG",
    email: "oif@francophonie.org",
    phone: "+33 1 44 37 33 00",
    totalSent: 22,
    totalReceived: 19,
    lastExchangeDate: new Date("2026-03-30T09:00:00"),
    mails: [
      {
        id: "m-003-a",
        reference: "ARR-2026-03-30-0001",
        receivedAt: new Date("2026-03-30T09:00:00"),
        emittedAt: new Date("2026-03-29T12:00:00"),
        sender: "Organisation Internationale de la Francophonie (OIF)",
        senderType: "ONG",
        senderOrganization: "Secrétariat Général",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Convocation à la 45ème session de la Conférence ministérielle de la Francophonie",
        type: "COURRIER_ARRIVEE",
        priority: "URGENT",
        confidentiality: "CONFIDENTIEL",
        status: "EN_TRAITEMENT",
        pageCount: 8,
        registeredBy: "Agent Koné",
        read: true,
      },
      {
        id: "m-003-b",
        reference: "DEP-2026-03-22-0005",
        receivedAt: new Date("2026-03-22T11:00:00"),
        emittedAt: new Date("2026-03-21T15:00:00"),
        sender: "Secrétariat Permanent - CNF",
        senderType: "ADMINISTRATION",
        senderOrganization: "Direction de la Coopération",
        recipientService: "OIF - Secrétariat Général",
        object:
          "Rapport national sur la mise en œuvre du programme de coopération multilatérale",
        type: "COURRIER_DEPART",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "TRANSMIS",
        pageCount: 30,
        registeredBy: "Agent Sylla",
        read: true,
      },
    ],
  },
  {
    id: "corr-004",
    name: "Ministère des Affaires Étrangères",
    type: "ADMINISTRATION",
    email: "diplomatie@mae.gouv.ci",
    phone: "+225 27 20 32 65 00",
    totalSent: 15,
    totalReceived: 10,
    lastExchangeDate: new Date("2026-03-18T08:30:00"),
    mails: [
      {
        id: "m-004-a",
        reference: "DEP-2026-03-18-0004",
        receivedAt: new Date("2026-03-18T08:30:00"),
        emittedAt: new Date("2026-03-17T11:00:00"),
        sender: "Secrétariat Permanent - CNF",
        senderType: "ADMINISTRATION",
        senderOrganization: "Secrétariat Permanent",
        recipientService: "Ministère des Affaires Étrangères",
        object:
          "Transmission du rapport annuel de coopération multilatérale francophone",
        type: "COURRIER_DEPART",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "ARCHIVE",
        pageCount: 15,
        registeredBy: "Agent Bamba",
        read: true,
      },
      {
        id: "m-004-b",
        reference: "ARR-2026-03-05-0019",
        receivedAt: new Date("2026-03-05T14:30:00"),
        emittedAt: new Date("2026-03-04T10:00:00"),
        sender: "Ministère des Affaires Étrangères",
        senderType: "ADMINISTRATION",
        senderOrganization: "Direction de la Coopération Multilatérale",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Instructions pour la préparation du Sommet de la Francophonie 2026",
        type: "COURRIER_ARRIVEE",
        priority: "TRES_URGENT",
        confidentiality: "SECRET",
        status: "EN_TRAITEMENT",
        pageCount: 6,
        registeredBy: "Agent Koné",
        read: true,
      },
    ],
  },
  {
    id: "corr-005",
    name: "TV5 Monde",
    type: "ENTREPRISE",
    email: "contact@tv5monde.com",
    phone: "+33 1 44 18 55 55",
    totalSent: 3,
    totalReceived: 5,
    lastExchangeDate: new Date("2026-03-12T16:00:00"),
    mails: [
      {
        id: "m-005-a",
        reference: "ARR-2026-03-12-0022",
        receivedAt: new Date("2026-03-12T16:00:00"),
        emittedAt: new Date("2026-03-11T09:00:00"),
        sender: "TV5 Monde",
        senderType: "ENTREPRISE",
        senderOrganization: "Direction de la Communication",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Proposition de couverture médiatique de la Semaine de la Francophonie",
        type: "COURRIER_ARRIVEE",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "CLOTURE",
        pageCount: 2,
        registeredBy: "Agent Sylla",
        read: true,
      },
    ],
  },
  {
    id: "corr-006",
    name: "Direction des Ressources Humaines",
    type: "ADMINISTRATION",
    email: "drh@cnf.gouv.ci",
    phone: "+225 05 55 55 55 55",
    totalSent: 6,
    totalReceived: 9,
    lastExchangeDate: new Date("2026-03-27T14:15:00"),
    mails: [
      {
        id: "m-006-a",
        reference: "INT-2026-03-27-0045",
        receivedAt: new Date("2026-03-27T14:15:00"),
        emittedAt: new Date("2026-03-26T10:00:00"),
        sender: "Direction des Ressources Humaines",
        senderType: "ADMINISTRATION",
        senderOrganization: "DRH - CNF",
        recipientService: "Tous les Départements",
        object:
          "Note de service : nouvelles modalités de formation continue des agents",
        type: "NOTE_INTERNE",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "TRANSMIS",
        pageCount: 1,
        registeredBy: "Agent Sylla",
        read: true,
      },
      {
        id: "m-006-b",
        reference: "INT-2026-03-15-0030",
        receivedAt: new Date("2026-03-15T11:00:00"),
        emittedAt: new Date("2026-03-14T09:00:00"),
        sender: "Direction des Ressources Humaines",
        senderType: "ADMINISTRATION",
        senderOrganization: "DRH - CNF",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Programme de bourses de mobilité dans l'espace francophone — appel à candidatures",
        type: "NOTE_INTERNE",
        priority: "URGENT",
        confidentiality: "NORMAL",
        status: "CLOTURE",
        pageCount: 3,
        registeredBy: "Agent Bamba",
        read: true,
      },
    ],
  },
  {
    id: "corr-007",
    name: "Ambassade de France en Côte d'Ivoire",
    type: "ADMINISTRATION",
    email: "ambafrance@diplomatie.gouv.fr",
    phone: "+225 27 20 20 04 04",
    totalSent: 9,
    totalReceived: 7,
    lastExchangeDate: new Date("2026-03-22T10:00:00"),
    mails: [
      {
        id: "m-007-a",
        reference: "ARR-2026-03-22-0018",
        receivedAt: new Date("2026-03-22T10:00:00"),
        emittedAt: new Date("2026-03-21T08:30:00"),
        sender: "Ambassade de France en Côte d'Ivoire",
        senderType: "ADMINISTRATION",
        senderOrganization: "Service de Coopération et d'Action Culturelle",
        recipientService: "Secrétariat Permanent - CNF",
        object:
          "Invitation à la réception diplomatique pour la célébration de la Journée de la Francophonie",
        type: "COURRIER_ARRIVEE",
        priority: "NORMAL",
        confidentiality: "CONFIDENTIEL",
        status: "CLOTURE",
        pageCount: 1,
        registeredBy: "Agent Koné",
        read: true,
      },
    ],
  },
  {
    id: "corr-008",
    name: "Université Félix Houphouët-Boigny",
    type: "ADMINISTRATION",
    email: "presidence@univ-fhb.edu.ci",
    phone: "+225 27 22 44 90 00",
    totalSent: 4,
    totalReceived: 6,
    lastExchangeDate: new Date("2026-03-08T09:45:00"),
    mails: [
      {
        id: "m-008-a",
        reference: "ARR-2026-03-08-0014",
        receivedAt: new Date("2026-03-08T09:45:00"),
        emittedAt: new Date("2026-03-07T14:00:00"),
        sender: "Université Félix Houphouët-Boigny",
        senderType: "ADMINISTRATION",
        senderOrganization: "Présidence de l'Université",
        recipientService: "Département de la Promotion de la Langue",
        object:
          "Demande d'appui pour le lancement du Master en Sciences du Langage et Francophonie",
        type: "COURRIER_ARRIVEE",
        priority: "NORMAL",
        confidentiality: "NORMAL",
        status: "EN_TRAITEMENT",
        pageCount: 4,
        registeredBy: "Agent Bamba",
        read: false,
      },
    ],
  },
];
